[[main]]
 name = "Über"
 pageRef = "about"
 weight = 10

[[main]]
 name = "Projekte"
 pageRef = "projects"
 weight = 20

[[main]]
  identifier = "github2"
  pre = "github"
  url = "https://github.com/zotko"
  weight = 30

 [[footer]]
  name = "🇺🇦 #StandWithUkraine"
  url = "https://stand-with-ukraine.pp.ua"
  weight = 10
