[[main]]
 name = "Über"
 pageRef = "about"
 weight = 10

[[main]]
 name = "Leistungen"
 pageRef = "services"
 weight = 20

[[main]]
 name = "Projekte"
 pageRef = "projects"
 weight = 30

 [[footer]]
  name = "🇺🇦 #StandWithUkraine"
  url = "https://stand-with-ukraine.pp.ua"
  weight = 10
