[hugoVersion]
  extended = false
  min = "0.139.3"

[[imports]]
  path = "github.com/hugomods/icons"

[[imports]]
  path = "github.com/hugomods/icons/vendors/devicons"

[[imports]]
  path = "github.com/hugomods/icons/vendors/simple-icons"

[[imports]]
  path = "github.com/hugomods/icons/vendors/lucide"
  
